org: camilaespinoza
service: alerta-utec

provider:
  name: aws
  runtime: python3.10
  memorySize: 256
  timeout: 20
  region: us-east-1
  role: 197052065931

functions:
  crear_incidente:
    handler: app.crear_incidente
    events:
      - http:
          path: /incidentes
          method: post
          cors: true

  listar_incidentes:
    handler: app.listar_incidentes
    events:
      - http:
          path: /incidentes
          method: get
          cors: true

  obtener_incidente:
    handler: app.obtener_incidente
    events:
      - http:
          path: /incidentes/{id}
          method: get
          cors: true

  actualizar_incidente:
    handler: app.actualizar_incidente
    events:
      - http:
          path: /incidentes/{id}
          method: put
          cors: true

resources:
  Resources:
    IncidentesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IncidentesUTEC
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
